# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wear_type', models.IntegerField(choices=[(1, 'T-Shirt'), (2, 'Sweater'), (3, 'Hat')])),
                ('description', models.TextField(blank=True, max_length=250)),
                ('design', models.IntegerField(choices=[(1, 'Small Logo'), (2, 'Big Logo')])),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
