# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 15:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20170930_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='rel_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 9, 30, 17, 58, 10, 403641)),
        ),
    ]
