# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20170930_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='rel_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
