# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0001_initial'),
        ('social', '0004_auto_20170930_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchPossession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_date', models.DateField(default=django.utils.timezone.now)),
                ('merch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merch_possessed', to='merch.Merch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_possessing', to='social.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='merchPossession',
            field=models.ManyToManyField(related_name='merch_possession', through='social.MerchPossession', to='social.Profile'),
        ),
    ]
