# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20171004_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='merchPossession',
            new_name='merchPossessions',
        ),
    ]
