# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20171004_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='merchPossessions',
        ),
    ]
